<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['shortname'=>'AF', 'name'=>'Afghanistan', 'phonecode'=>93],
            ['shortname'=>'AL', 'name'=>'Albania', 'phonecode'=>355],
            ['shortname'=>'DZ', 'name'=>'Algeria', 'phonecode'=>213],
            ['shortname'=>'AS', 'name'=>'American Samoa', 'phonecode'=>1684],
            ['shortname'=>'AD', 'name'=>'Andorra', 'phonecode'=>376],
            ['shortname'=>'AO', 'name'=>'Angola', 'phonecode'=>244],
            ['shortname'=>'AI', 'name'=>'Anguilla', 'phonecode'=>1264],
            ['shortname'=>'AQ', 'name'=>'Antarctica', 'phonecode'=>0],
            ['shortname'=>'AG', 'name'=>'Antigua And Barbuda', 'phonecode'=>1268],
            ['shortname'=>'AR', 'name'=>'Argentina', 'phonecode'=>54],
            ['shortname'=>'AM', 'name'=>'Armenia', 'phonecode'=>374],
            ['shortname'=>'AW', 'name'=>'Aruba', 'phonecode'=>297],
            ['shortname'=>'AU', 'name'=>'Australia', 'phonecode'=>61],
            ['shortname'=>'AT', 'name'=>'Austria', 'phonecode'=>43],
            ['shortname'=>'AZ', 'name'=>'Azerbaijan', 'phonecode'=>994],
            ['shortname'=>'BS', 'name'=>'Bahamas The', 'phonecode'=>1242],
            ['shortname'=>'BH', 'name'=>'Bahrain', 'phonecode'=>973],
            ['shortname'=>'BD', 'name'=>'Bangladesh', 'phonecode'=>880],
            ['shortname'=>'BB', 'name'=>'Barbados', 'phonecode'=>1246],
            ['shortname'=>'BY', 'name'=>'Belarus', 'phonecode'=>375],
            ['shortname'=>'BE', 'name'=>'Belgium', 'phonecode'=>32],
            ['shortname'=>'BZ', 'name'=>'Belize', 'phonecode'=>501],
            ['shortname'=>'BJ', 'name'=>'Benin', 'phonecode'=>229],
            ['shortname'=>'BM', 'name'=>'Bermuda', 'phonecode'=>1441],
            ['shortname'=>'BT', 'name'=>'Bhutan', 'phonecode'=>975],
            ['shortname'=>'BO', 'name'=>'Bolivia', 'phonecode'=>591],
            ['shortname'=>'BA', 'name'=>'Bosnia and Herzegovina', 'phonecode'=>387],
            ['shortname'=>'BW', 'name'=>'Botswana', 'phonecode'=>267],
            ['shortname'=>'BV', 'name'=>'Bouvet Island', 'phonecode'=>0],
            ['shortname'=>'BR', 'name'=>'Brazil', 'phonecode'=>55],
            ['shortname'=>'IO', 'name'=>'British Indian Ocean Territory', 'phonecode'=>246],
            ['shortname'=>'BN', 'name'=>'Brunei', 'phonecode'=>673],
            ['shortname'=>'BG', 'name'=>'Bulgaria', 'phonecode'=>359],
            ['shortname'=>'BF', 'name'=>'Burkina Faso', 'phonecode'=>226],
            ['shortname'=>'BI', 'name'=>'Burundi', 'phonecode'=>257],
            ['shortname'=>'KH', 'name'=>'Cambodia', 'phonecode'=>855],
            ['shortname'=>'CM', 'name'=>'Cameroon', 'phonecode'=>237],
            ['shortname'=>'CA', 'name'=>'Canada', 'phonecode'=>1],
            ['shortname'=>'CV', 'name'=>'Cape Verde', 'phonecode'=>238],
            ['shortname'=>'KY', 'name'=>'Cayman Islands', 'phonecode'=>1345],
            ['shortname'=>'CF', 'name'=>'Central African Republic', 'phonecode'=>236],
            ['shortname'=>'TD', 'name'=>'Chad', 'phonecode'=>235],
            ['shortname'=>'CL', 'name'=>'Chile', 'phonecode'=>56],
            ['shortname'=>'CN', 'name'=>'China', 'phonecode'=>86],
            ['shortname'=>'CX', 'name'=>'Christmas Island', 'phonecode'=>61],
            ['shortname'=>'CC', 'name'=>'Cocos (Keeling) Islands', 'phonecode'=>672],
            ['shortname'=>'CO', 'name'=>'Colombia', 'phonecode'=>57],
            ['shortname'=>'KM', 'name'=>'Comoros', 'phonecode'=>269],
            ['shortname'=>'CG', 'name'=>'Republic Of The Congo', 'phonecode'=>242],
            ['shortname'=>'CD', 'name'=>'Democratic Republic Of The Congo', 'phonecode'=>242],
            ['shortname'=>'CK', 'name'=>'Cook Islands', 'phonecode'=>682],
            ['shortname'=>'CR', 'name'=>'Costa Rica', 'phonecode'=>506],
            ['shortname'=>'CI', 'name'=>'Cote D\'Ivoire (Ivory Coast)', 'phonecode'=>225],
            ['shortname'=>'HR', 'name'=>'Croatia (Hrvatska)', 'phonecode'=>385],
            ['shortname'=>'CU', 'name'=>'Cuba', 'phonecode'=>53],
            ['shortname'=>'CY', 'name'=>'Cyprus', 'phonecode'=>357],
            ['shortname'=>'CZ', 'name'=>'Czech Republic', 'phonecode'=>420],
            ['shortname'=>'DK', 'name'=>'Denmark', 'phonecode'=>45],
            ['shortname'=>'DJ', 'name'=>'Djibouti', 'phonecode'=>253],
            ['shortname'=>'DM', 'name'=>'Dominica', 'phonecode'=>1767],
            ['shortname'=>'DO', 'name'=>'Dominican Republic', 'phonecode'=>1809],
            ['shortname'=>'TP', 'name'=>'East Timor', 'phonecode'=>670],
            ['shortname'=>'EC', 'name'=>'Ecuador', 'phonecode'=>593],
            ['shortname'=>'EG', 'name'=>'Egypt', 'phonecode'=>20],
            ['shortname'=>'SV', 'name'=>'El Salvador', 'phonecode'=>503],
            ['shortname'=>'GQ', 'name'=>'Equatorial Guinea', 'phonecode'=>240],
            ['shortname'=>'ER', 'name'=>'Eritrea', 'phonecode'=>291],
            ['shortname'=>'EE', 'name'=>'Estonia', 'phonecode'=>372],
            ['shortname'=>'ET', 'name'=>'Ethiopia', 'phonecode'=>251],
            ['shortname'=>'XA', 'name'=>'External Territories of Australia', 'phonecode'=>61],
            ['shortname'=>'FK', 'name'=>'Falkland Islands', 'phonecode'=>500],
            ['shortname'=>'FO', 'name'=>'Faroe Islands', 'phonecode'=>298],
            ['shortname'=>'FJ', 'name'=>'Fiji Islands', 'phonecode'=>679],
            ['shortname'=>'FI', 'name'=>'Finland', 'phonecode'=>358],
            ['shortname'=>'FR', 'name'=>'France', 'phonecode'=>33],
            ['shortname'=>'GF', 'name'=>'French Guiana', 'phonecode'=>594],
            ['shortname'=>'PF', 'name'=>'French Polynesia', 'phonecode'=>689],
            ['shortname'=>'TF', 'name'=>'French Southern Territories', 'phonecode'=>0],
            ['shortname'=>'GA', 'name'=>'Gabon', 'phonecode'=>241],
            ['shortname'=>'GM', 'name'=>'Gambia The', 'phonecode'=>220],
            ['shortname'=>'GE', 'name'=>'Georgia', 'phonecode'=>995],
            ['shortname'=>'DE', 'name'=>'Germany', 'phonecode'=>49],
            ['shortname'=>'GH', 'name'=>'Ghana', 'phonecode'=>233],
            ['shortname'=>'GI', 'name'=>'Gibraltar', 'phonecode'=>350],
            ['shortname'=>'GR', 'name'=>'Greece', 'phonecode'=>30],
            ['shortname'=>'GL', 'name'=>'Greenland', 'phonecode'=>299],
            ['shortname'=>'GD', 'name'=>'Grenada', 'phonecode'=>1473],
            ['shortname'=>'GP', 'name'=>'Guadeloupe', 'phonecode'=>590],
            ['shortname'=>'GU', 'name'=>'Guam', 'phonecode'=>1671],
            ['shortname'=>'GT', 'name'=>'Guatemala', 'phonecode'=>502],
            ['shortname'=>'XU', 'name'=>'Guernsey and Alderney', 'phonecode'=>44],
            ['shortname'=>'GN', 'name'=>'Guinea', 'phonecode'=>224],
            ['shortname'=>'GW', 'name'=>'Guinea-Bissau', 'phonecode'=>245],
            ['shortname'=>'GY', 'name'=>'Guyana', 'phonecode'=>592],
            ['shortname'=>'HT', 'name'=>'Haiti', 'phonecode'=>509],
            ['shortname'=>'HM', 'name'=>'Heard and McDonald Islands', 'phonecode'=>0],
            ['shortname'=>'HN', 'name'=>'Honduras', 'phonecode'=>504],
            ['shortname'=>'HK', 'name'=>'Hong Kong S.A.R.', 'phonecode'=>852],
            ['shortname'=>'HU', 'name'=>'Hungary', 'phonecode'=>36],
            ['shortname'=>'IS', 'name'=>'Iceland', 'phonecode'=>354],
            ['shortname'=>'IN', 'name'=>'India', 'phonecode'=>91],
            ['shortname'=>'ID', 'name'=>'Indonesia', 'phonecode'=>62],
            ['shortname'=>'IR', 'name'=>'Iran', 'phonecode'=>98],
            ['shortname'=>'IQ', 'name'=>'Iraq', 'phonecode'=>964],
            ['shortname'=>'IE', 'name'=>'Ireland', 'phonecode'=>353],
            ['shortname'=>'IL', 'name'=>'Israel', 'phonecode'=>972],
            ['shortname'=>'IT', 'name'=>'Italy', 'phonecode'=>39],
            ['shortname'=>'JM', 'name'=>'Jamaica', 'phonecode'=>1876],
            ['shortname'=>'JP', 'name'=>'Japan', 'phonecode'=>81],
            ['shortname'=>'XJ', 'name'=>'Jersey', 'phonecode'=>44],
            ['shortname'=>'JO', 'name'=>'Jordan', 'phonecode'=>962],
            ['shortname'=>'KZ', 'name'=>'Kazakhstan', 'phonecode'=>7],
            ['shortname'=>'KE', 'name'=>'Kenya', 'phonecode'=>254],
            ['shortname'=>'KI', 'name'=>'Kiribati', 'phonecode'=>686],
            ['shortname'=>'KP', 'name'=>'Korea North', 'phonecode'=>850],
            ['shortname'=>'KR', 'name'=>'Korea South', 'phonecode'=>82],
            ['shortname'=>'KW', 'name'=>'Kuwait', 'phonecode'=>965],
            ['shortname'=>'KG', 'name'=>'Kyrgyzstan', 'phonecode'=>996],
            ['shortname'=>'LA', 'name'=>'Laos', 'phonecode'=>856],
            ['shortname'=>'LV', 'name'=>'Latvia', 'phonecode'=>371],
            ['shortname'=>'LB', 'name'=>'Lebanon', 'phonecode'=>961],
            ['shortname'=>'LS', 'name'=>'Lesotho', 'phonecode'=>266],
            ['shortname'=>'LR', 'name'=>'Liberia', 'phonecode'=>231],
            ['shortname'=>'LY', 'name'=>'Libya', 'phonecode'=>218],
            ['shortname'=>'LI', 'name'=>'Liechtenstein', 'phonecode'=>423],
            ['shortname'=>'LT', 'name'=>'Lithuania', 'phonecode'=>370],
            ['shortname'=>'LU', 'name'=>'Luxembourg', 'phonecode'=>352],
            ['shortname'=>'MO', 'name'=>'Macau S.A.R.', 'phonecode'=>853],
            ['shortname'=>'MK', 'name'=>'Macedonia', 'phonecode'=>389],
            ['shortname'=>'MG', 'name'=>'Madagascar', 'phonecode'=>261],
            ['shortname'=>'MW', 'name'=>'Malawi', 'phonecode'=>265],
            ['shortname'=>'MY', 'name'=>'Malaysia', 'phonecode'=>60],
            ['shortname'=>'MV', 'name'=>'Maldives', 'phonecode'=>960],
            ['shortname'=>'ML', 'name'=>'Mali', 'phonecode'=>223],
            ['shortname'=>'MT', 'name'=>'Malta', 'phonecode'=>356],
            ['shortname'=>'XM', 'name'=>'Man (Isle of)', 'phonecode'=>44],
            ['shortname'=>'MH', 'name'=>'Marshall Islands', 'phonecode'=>692],
            ['shortname'=>'MQ', 'name'=>'Martinique', 'phonecode'=>596],
            ['shortname'=>'MR', 'name'=>'Mauritania', 'phonecode'=>222],
            ['shortname'=>'MU', 'name'=>'Mauritius', 'phonecode'=>230],
            ['shortname'=>'YT', 'name'=>'Mayotte', 'phonecode'=>269],
            ['shortname'=>'MX', 'name'=>'Mexico', 'phonecode'=>52],
            ['shortname'=>'FM', 'name'=>'Micronesia', 'phonecode'=>691],
            ['shortname'=>'MD', 'name'=>'Moldova', 'phonecode'=>373],
            ['shortname'=>'MC', 'name'=>'Monaco', 'phonecode'=>377],
            ['shortname'=>'MN', 'name'=>'Mongolia', 'phonecode'=>976],
            ['shortname'=>'MS', 'name'=>'Montserrat', 'phonecode'=>1664],
            ['shortname'=>'MA', 'name'=>'Morocco', 'phonecode'=>212],
            ['shortname'=>'MZ', 'name'=>'Mozambique', 'phonecode'=>258],
            ['shortname'=>'MM', 'name'=>'Myanmar', 'phonecode'=>95],
            ['shortname'=>'NA', 'name'=>'Namibia', 'phonecode'=>264],
            ['shortname'=>'NR', 'name'=>'Nauru', 'phonecode'=>674],
            ['shortname'=>'NP', 'name'=>'Nepal', 'phonecode'=>977],
            ['shortname'=>'AN', 'name'=>'Netherlands Antilles', 'phonecode'=>599],
            ['shortname'=>'NL', 'name'=>'Netherlands The', 'phonecode'=>31],
            ['shortname'=>'NC', 'name'=>'New Caledonia', 'phonecode'=>687],
            ['shortname'=>'NZ', 'name'=>'New Zealand', 'phonecode'=>64],
            ['shortname'=>'NI', 'name'=>'Nicaragua', 'phonecode'=>505],
            ['shortname'=>'NE', 'name'=>'Niger', 'phonecode'=>227],
            ['shortname'=>'NG', 'name'=>'Nigeria', 'phonecode'=>234],
            ['shortname'=>'NU', 'name'=>'Niue', 'phonecode'=>683],
            ['shortname'=>'NF', 'name'=>'Norfolk Island', 'phonecode'=>672],
            ['shortname'=>'MP', 'name'=>'Northern Mariana Islands', 'phonecode'=>1670],
            ['shortname'=>'NO', 'name'=>'Norway', 'phonecode'=>47],
            ['shortname'=>'OM', 'name'=>'Oman', 'phonecode'=>968],
            ['shortname'=>'PK', 'name'=>'Pakistan', 'phonecode'=>92],
            ['shortname'=>'PW', 'name'=>'Palau', 'phonecode'=>680],
            ['shortname'=>'PS', 'name'=>'Palestinian Territory Occupied', 'phonecode'=>970],
            ['shortname'=>'PA', 'name'=>'Panama', 'phonecode'=>507],
            ['shortname'=>'PG', 'name'=>'Papua new Guinea', 'phonecode'=>675],
            ['shortname'=>'PY', 'name'=>'Paraguay', 'phonecode'=>595],
            ['shortname'=>'PE', 'name'=>'Peru', 'phonecode'=>51],
            ['shortname'=>'PH', 'name'=>'Philippines', 'phonecode'=>63],
            ['shortname'=>'PN', 'name'=>'Pitcairn Island', 'phonecode'=>0],
            ['shortname'=>'PL', 'name'=>'Poland', 'phonecode'=>48],
            ['shortname'=>'PT', 'name'=>'Portugal', 'phonecode'=>351],
            ['shortname'=>'PR', 'name'=>'Puerto Rico', 'phonecode'=>1787],
            ['shortname'=>'QA', 'name'=>'Qatar', 'phonecode'=>974],
            ['shortname'=>'RE', 'name'=>'Reunion', 'phonecode'=>262],
            ['shortname'=>'RO', 'name'=>'Romania', 'phonecode'=>40],
            ['shortname'=>'RU', 'name'=>'Russia', 'phonecode'=>70],
            ['shortname'=>'RW', 'name'=>'Rwanda', 'phonecode'=>250],
            ['shortname'=>'SH', 'name'=>'Saint Helena', 'phonecode'=>290],
            ['shortname'=>'KN', 'name'=>'Saint Kitts And Nevis', 'phonecode'=>1869],
            ['shortname'=>'LC', 'name'=>'Saint Lucia', 'phonecode'=>1758],
            ['shortname'=>'PM', 'name'=>'Saint Pierre and Miquelon', 'phonecode'=>508],
            ['shortname'=>'VC', 'name'=>'Saint Vincent And The Grenadines', 'phonecode'=>1784],
            ['shortname'=>'WS', 'name'=>'Samoa', 'phonecode'=>684],
            ['shortname'=>'SM', 'name'=>'San Marino', 'phonecode'=>378],
            ['shortname'=>'ST', 'name'=>'Sao Tome and Principe', 'phonecode'=>239],
            ['shortname'=>'SA', 'name'=>'Saudi Arabia', 'phonecode'=>966],
            ['shortname'=>'SN', 'name'=>'Senegal', 'phonecode'=>221],
            ['shortname'=>'RS', 'name'=>'Serbia', 'phonecode'=>381],
            ['shortname'=>'SC', 'name'=>'Seychelles', 'phonecode'=>248],
            ['shortname'=>'SL', 'name'=>'Sierra Leone', 'phonecode'=>232],
            ['shortname'=>'SG', 'name'=>'Singapore', 'phonecode'=>65],
            ['shortname'=>'SK', 'name'=>'Slovakia', 'phonecode'=>421],
            ['shortname'=>'SI', 'name'=>'Slovenia', 'phonecode'=>386],
            ['shortname'=>'XG', 'name'=>'Smaller Territories of the UK', 'phonecode'=>44],
            ['shortname'=>'SB', 'name'=>'Solomon Islands', 'phonecode'=>677],
            ['shortname'=>'SO', 'name'=>'Somalia', 'phonecode'=>252],
            ['shortname'=>'ZA', 'name'=>'South Africa', 'phonecode'=>27],
            ['shortname'=>'GS', 'name'=>'South Georgia', 'phonecode'=>0],
            ['shortname'=>'SS', 'name'=>'South Sudan', 'phonecode'=>211],
            ['shortname'=>'ES', 'name'=>'Spain', 'phonecode'=>34],
            ['shortname'=>'LK', 'name'=>'Sri Lanka', 'phonecode'=>94],
            ['shortname'=>'SD', 'name'=>'Sudan', 'phonecode'=>249],
            ['shortname'=>'SR', 'name'=>'Suriname', 'phonecode'=>597],
            ['shortname'=>'SJ', 'name'=>'Svalbard And Jan Mayen Islands', 'phonecode'=>47],
            ['shortname'=>'SZ', 'name'=>'Swaziland', 'phonecode'=>268],
            ['shortname'=>'SE', 'name'=>'Sweden', 'phonecode'=>46],
            ['shortname'=>'CH', 'name'=>'Switzerland', 'phonecode'=>41],
            ['shortname'=>'SY', 'name'=>'Syria', 'phonecode'=>963],
            ['shortname'=>'TW', 'name'=>'Taiwan', 'phonecode'=>886],
            ['shortname'=>'TJ', 'name'=>'Tajikistan', 'phonecode'=>992],
            ['shortname'=>'TZ', 'name'=>'Tanzania', 'phonecode'=>255],
            ['shortname'=>'TH', 'name'=>'Thailand', 'phonecode'=>66],
            ['shortname'=>'TG', 'name'=>'Togo', 'phonecode'=>228],
            ['shortname'=>'TK', 'name'=>'Tokelau', 'phonecode'=>690],
            ['shortname'=>'TO', 'name'=>'Tonga', 'phonecode'=>676],
            ['shortname'=>'TT', 'name'=>'Trinidad And Tobago', 'phonecode'=>1868],
            ['shortname'=>'TN', 'name'=>'Tunisia', 'phonecode'=>216],
            ['shortname'=>'TR', 'name'=>'Turkey', 'phonecode'=>90],
            ['shortname'=>'TM', 'name'=>'Turkmenistan', 'phonecode'=>7370],
            ['shortname'=>'TC', 'name'=>'Turks And Caicos Islands', 'phonecode'=>1649],
            ['shortname'=>'TV', 'name'=>'Tuvalu', 'phonecode'=>688],
            ['shortname'=>'UG', 'name'=>'Uganda', 'phonecode'=>256],
            ['shortname'=>'UA', 'name'=>'Ukraine', 'phonecode'=>380],
            ['shortname'=>'AE', 'name'=>'United Arab Emirates', 'phonecode'=>971],
            ['shortname'=>'GB', 'name'=>'United Kingdom', 'phonecode'=>44],
            ['shortname'=>'US', 'name'=>'United States', 'phonecode'=>1],
            ['shortname'=>'UM', 'name'=>'United States Minor Outlying Islands', 'phonecode'=>1],
            ['shortname'=>'UY', 'name'=>'Uruguay', 'phonecode'=>598],
            ['shortname'=>'UZ', 'name'=>'Uzbekistan', 'phonecode'=>998],
            ['shortname'=>'VU', 'name'=>'Vanuatu', 'phonecode'=>678],
            ['shortname'=>'VA', 'name'=>'Vatican City State (Holy See)', 'phonecode'=>39],
            ['shortname'=>'VE', 'name'=>'Venezuela', 'phonecode'=>58],
            ['shortname'=>'VN', 'name'=>'Vietnam', 'phonecode'=>84],
            ['shortname'=>'VG', 'name'=>'Virgin Islands (British)', 'phonecode'=>1284],
            ['shortname'=>'VI', 'name'=>'Virgin Islands (US)', 'phonecode'=>1340],
            ['shortname'=>'WF', 'name'=>'Wallis And Futuna Islands', 'phonecode'=>681],
            ['shortname'=>'EH', 'name'=>'Western Sahara', 'phonecode'=>212],
            ['shortname'=>'YE', 'name'=>'Yemen', 'phonecode'=>967],
            ['shortname'=>'YU', 'name'=>'Yugoslavia', 'phonecode'=>38],
            ['shortname'=>'ZM', 'name'=>'Zambia', 'phonecode'=>260],
            ['shortname'=>'ZW', 'name'=>'Zimbabwe', 'phonecode'=>263]
        ];

        foreach ($countries as $key => $value) {
            Country::create($value);
        }
    }
}
